apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql-as
  labels:
    app: mysql
spec:
  imagePullSecrets:
    - name: ecr-secret
  containers:
  - name: mysql
    image: mysql:8.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"   # for test only; production: will use secrets.
    - name: MYSQL_DATABASE
      value: employees
    ports:
    - containerPort: 3306
